language: python
python:
  - "3.5"
  - "3.6"

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database django_test;' -U postgres

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

after_success:
  coveralls